spring:
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    username: ""
    password: ""
    url: "jdbc:h2:./test"
    show-sql: true

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

image-directory: C:\Users\datfe\testImages
