server:
  servlet:
    context-path: /api/v1
  port: 8000

spring:
  profiles:
    active: prod

spring-doc:
  swagger-ui:
    path: /api-docs.html

jwt-secret: iufjvgdsbYGB23U4BKQB8CJHbjfdsbb82134b1bfdksjwb819234bfjhsbfj32b487b
